### PR TITLE
Query class

### PR DESCRIPTION
**Pull request by matibat**
### Changes

- Cleans code & refactors types, typeguards and type conditionals;
- Has an incomplete transaction-like structure to hold the queried values;
- Has a parameters array for setting the response parameters
- Auto-handles the nextPage property
- Auto-manages the min block value related to the lastBlock (if defined)
- Max-tries limit & backup server
- Implements methods to the raw transaction (query.getRaw()) and the FSEntity(query<The type>.get())

### CODE REVIEW

**Review by agsuy — CHANGES_REQUESTED** [review]
Please rework _getSerializedTransactionData without the "IF"s

**Comment by matibat** [comment]
Check it now

**Comment by matibat** [comment]
Now:
- synced with dev

**Comment by matibat** [comment]
The changes on types (implementing classes) now sets the properties' defaults to invalid (= 'invalid').
This makes us have cleaner constructors, just used for calling `Object.assign(this, args)` to set the initial values. This is a generic approach intended to work with any derivated class.

**Comment by matibat** [comment]
Changes:

- Most of all queries replaced. Just missing getFileMetaDataFromTx(), which might be deleted after a better implementation of getAllMyDataFileTxs() to make it return directly the entities (already done, just need to be implemented)
- Private queries won't (yet) decrypt any data. **Let's see if we create a method for decrypting those to respect the SRP**
- All broken methods/types are at toDaemon/ folder

**Review by jdaev — APPROVED** [review]
Looks good to me

**Comment by matibat** [comment]
Now all query methods that doesn't require decryption works well at CLI

**Comment by matibat** [comment]
Now all query methods that doesn't require decryption works well at CLI

**Review by jdaev — APPROVED** [review]
Looks good

**Review by arielmelendez — CHANGES_REQUESTED** [review]
Let's hold off on merging this. It's far too large for most of the team to comprehend. Let's talk more about that and the possibilities for moving forward later today. Thanks!

**Pull request closed without merging**
